title: "/var/log/balo"
tagline: "Permission denied to call method PandorasBox.open"
url: "http://blog.varga.io"
feed: "http://feeds.feedburner.com/var-log-balo"
author:
    name: "Balazs Varga"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html
paginate_path: 'page/:num'
paginate: 2
timezone: Europe/Budapest

gems:
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "balo"
      layout: "post"
