title: "/var/log/balo"
tagline: "Permission denied to call method PandorasBox.open"
assets_uri: "https://s3.amazonaws.com/vbalazs-site-assets"
url: "https://vbalazs.github.io"
feed: "https://feeds.feedburner.com/var-log-balo"
author:
    name: "Balazs Varga"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html
paginate_path: 'page/:num'
paginate: 2
timezone: Europe/Budapest

plugins:
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "balo"
      layout: "post"
