title: "/var/log/balo"
tagline: "Permission denied to call method PandorasBox.open"
url: "http://blog.vbalazs.me"
feed: "http://feeds.feedburner.com/var-log-balo"
author:
    name: "Balazs Varga"
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:title.html
paginate_path: 'page/:num'
paginate: 2
timezone: Europe/Budapest

redcarpet:
    extensions:
        - autolink
        - strikethrough
        - no_intra_emphasis

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      author: "balo"
      layout: "post"
